<?php

$allPNPools = [
    '3rd Party Account Management',
    'A&BS - Accounting, HR & Legal',
    'A&BS - Ceased line final fees',
    'A&BS - Cheque Refunds',
    'A&BS - Cheques awaiting allocation',
    'A&BS - Debt Recovery Final Fees',
    'A&BS - Debt Recovery Removals',
    'A&BS - Debt Recovery Requests',
    'A&BS - Deferred Activation Cance',
    'A&BS - Direct Debit Mandate Requests',
    'A&BS - DR Automated',
    'A&BS - HLE (Finance use only)',
    'A&BS - Mac Key Payments due',
    'A&BS - No longer in use',
    'A&BS - Part Payment Requests',
    'A&BS - Partner Accounts',
    'A&BS - Re-provide Auth',
    'A&BS - Refund Investigation',
    'A&BS - Waitrose RTC vouchers',
    'A&BS – V@H Paper Billing',
    'A&BS- Direct Debit Failed',
    'ABS - Debt Recovery Final Fees',
    'ABS - Deferred Contracts',
    'Automated Script Pool',
    'Billing Accuracy - Missing TV Hardware',
    'Billing Operations - Billing Discounts',
    'Billing Operations - Billing, Refunds and Credits',
    'Billing Operations - Braille, Large Print or Audio Invoices',
    'Billing Operations - Chargebacks',
    'Billing Operations - Cheque refunds',
    'Billing Operations - Cheques awaiting allocation',
    'Billing-Ops-BT Sport Failed Payments',
    'Billing-Ops-BT Sport Re-Activation',
    'BOT - ADSL Cease Requests',
    'BOT - Asset Checks',
    'BOT - Bauer Agent to Agent',
    'BOT - Bauer CS',
    'BOT - Bauer Prov',
    'BOT - Brand Migrations',
    'BOT - Delayed Orders',
    'BOT - Dispute No Access',
    'BOT - Driver Requests',
    'BOT - DSL Faults',
    'BOT - DSL Logged Appointments ADSL2',
    'BOT - DSL Logged Faults',
    'BOT - DSL Logged Faults - Auth',
    'BOT - DSL Logged Faults - Auth Enhanced Care',
    'BOT - DSL Logged Faults - Banding',
    'BOT - DSL Logged Faults - Escala',
    'BOT - DSL Logged Faults - Escala Enhanced Care',
    'BOT - DSL Logged Faults - Interm',
    'BOT - DSL Logged Faults - Interm Enhanced Care',
    'BOT - DSL Logged Faults - LTB',
    'BOT - DSL Logged Faults - No Syn',
    'BOT - DSL Logged Faults - No Syn Enhanced Care',
    'BOT - DSL Logged Faults - Post SFI',
    'BOT - DSL Logged Faults - Priority Team',
    'BOT - DSL Logged Faults - Priority Team Escalated',
    'BOT - DSL Logged Faults - Retest',
    'BOT - DSL Logged Faults - Retest Enhanced Care',
    'BOT - DSL Logged Faults - SFI',
    'BOT - DSL Logged Faults - Speed',
    'BOT - DSL Logged Faults - Speed Enhanced Care',
    'BOT - DSL Logged Faults ADSL2',
    'BOT - DSL Logged Faults ADSL2 - Auth',
    'BOT - DSL Logged Faults ADSL2 - Esc',
    'BOT - DSL Logged Faults ADSL2 - Interm',
    'BOT - DSL Logged Faults ADSL2 - LTB',
    'BOT - DSL Logged Faults ADSL2 - No Sync',
    'BOT - DSL Logged Faults ADSL2 - Retest',
    'BOT - DSL Logged Faults ADSL2 - Speed',
    'BOT - DSL Logged Faults Enhanced Care',
    'BOT - DSL Migrations',
    'BOT - DSL Provisioning',
    'BOT - DSL Regrades',
    'BOT - DSL Regrades (Automated)',
    'BOT - End User DSL Logged Faults - Speed',
    'BOT - Engineer Charging disputes',
    'BOT - Escalated Appointments',
    'BOT - Expedite Orders',
    'BOT - Failed House Moves',
    'BOT - Fibre Problems',
    'BOT - Fibre Problems (Prov use only)',
    'BOT - FTTC Appointments',
    'BOT - FTTC Logged Faults',
    'BOT - FTTC Logged Faults - Appointments',
    'BOT - FTTC Logged Faults - Auth',
    'BOT - FTTC Logged Faults - Auth – Enhanced Care',
    'BOT - FTTC Logged Faults - Equip',
    'BOT - FTTC Logged Faults - Interm',
    'BOT - FTTC Logged Faults - Intermittent – Enhanced Care',
    'BOT - FTTC Logged Faults - LTB',
    'BOT - FTTC Logged Faults - No Sync',
    'BOT - FTTC Logged Faults - No Sync – Enhanced Care',
    'BOT - FTTC Logged Faults - Post SFI',
    'BOT - FTTC Logged Faults - Priority Escalated',
    'BOT - FTTC Logged Faults - Speed',
    'BOT - FTTC Logged Faults – Enhanced Care',
    'BOT - FTTC Logged Faults – Equipment – Enhanced Care',
    'BOT - FTTC Logged Faults – Speed – Enhanced Care',
    'BOT - FTTC Provides',
    'BOT - FTTC Provision Appointments',
    'BOT - FTTC Rejections',
    'BOT - HM Order placement',
    'BOT - Home Phone Nuisance Calls',
    'BOT - House Moves',
    'BOT - House Moves (In Progress)',
    'BOT - House Moves (Info required)',
    'BOT - House Moves BB Only',
    'BOT - House Moves NLI',
    'BOT - House Moves Start of Stop',
    'BOT - House Moves Transfer',
    'BOT - House Moves WLT',
    'BOT - ISDN Conversion Orde',
    'BOT - Line Check Exception',
    'BOT - Logged Faults - Priority Team',
    'BOT - MPF WLR2',
    'BOT - New BB Order Placement',
    'BOT - New PSTN Provides',
    'BOT - Openreach Engineer appointments',
    'BOT - Phone Automated Check Pool',
    'BOT - Phone Component',
    'BOT - Phone ELF',
    'BOT - Phone Faults',
    'BOT - Phone Faults - Logged',
    'BOT - Phone Faults - Logged Appointments',
    'BOT - Phone Faults - Migrations',
    'BOT - Phone Faults Escalations',
    'BOT - Phone Prov Cable Number port',
    'BOT - Phone Prov Cable Start of Stop',
    'BOT - Phone Provisioning',
    'BOT - Phone Provisioning 2',
    'BOT - Phone Provisioning automation exceptions',
    'BOT - Phone Provisioning Cable',
    'BOT - Phone Provisioning Checks',
    'BOT - Phone Provisioning MPF',
    'BOT - Phone provisioning WLT',
    'BOT - Phone Provisioning WLT SPG',
    'BOT - Priority DJ',
    'BOT - Priority GH',
    'BOT - Priority GR',
    'BOT - Priority MB',
    'BOT - Priority SW',
    'BOT - Provision Case Mgt BB',
    'BOT - Provision Case Mgt HP',
    'BOT - PSTN Escalations',
    'BOT - PSTN Manual Provisioning',
    'BOT - Regrades Due',
    'BOT - RMA Requests',
    'BOT - SDSL Faults',
    'BOT - SDSL Provisioning',
    'BOT - Simultaneous Provides',
    'BOT - Sky BT Sport cancellations',
    'BOT - Sky BT Sport card ordering',
    'BOT - Sky BT Sport customer service',
    'BOT - Sky BT Sport order placement',
    'BOT - Supplier Team',
    'BOT - Tags Queries',
    'BOT - TC DSL Provisioning',
    'BOT - TC Logged Faults - Esc',
    'BOT - TC Logged Faults - Retest',
    'BOT - TC Logged Faults - Updates',
    'BOT - TV Faults',
    'BOT - TV Provisioning',
    'BOT - Usage Resets',
    'BOT - WBMC Migrations',
    'BOT - WBMC Provisioning',
    'BOT - WLR 3 - Appointing',
    'BOT - WLR 3 - Cancelled Orders',
    'BOT - WLR 3 - Delayed Orders',
    'BOT - WLR 3 - Rejections',
    'BOT - WLR Appointment Changes',
    'BOT - WLR Directory Entry Changes',
    'BOT - WLR Feature Requests',
    'BOT - WLR Unsolicited Cease Cancellations',
    'BOT - WLR Worklist Items',
    'BOT - XML Rejections',
    'BOT TEST',
    'BOT WLR Provisioning Errors',
    'BOT – FTTC Appointments',
    'BOT – FTTC Provides',
    'BOT- Order Progress ONLY',
    'BOT-WLR MPF Delayed',
    'Broadband Update',
    'BT Integration',
    'BTITW - Hardware Ordering',
    'Business - Provisioning Care',
    'Business - Provsioning Care',
    'Cancellation - Mac',
    'Cashback',
    'Complaints - COT',
    'Complaints - Customer Services',
    'Complaints - Faults',
    'Complaints - Provisioning',
    'Complaints - Sales',
    'Complaints - Technical',
    'Complaints Advisor',
    'Consumer',
    'Consumer - FTTC PR Participation',
    'Content Team',
    'COT - Chat Use Only',
    'COT - Fibre to TV upgrade',
    'COT - HM CH',
    'COT - HM CW',
    'COT - HM DC',
    'COT - HM DG',
    'COT - HM Escalations',
    'COT - HM IN',
    'COT - HM JA',
    'COT - HM JF',
    'COT - HM JV',
    'COT - HM KW',
    'COT - HM LC',
    'COT - HM MC',
    'COT - HM MJ',
    'COT - HM Order placement',
    'COT - HM PL',
    'COT - HM RB',
    'COT - HM SC',
    'COT - HM SD',
    'COT - HM SH',
    'COT - HM SM',
    'COT - HM ST',
    'COT - OOH TV upgrades',
    'COT – HM OOH',
    'COT – HM Priority',
    'COT – HM Reactivation',
    'CS - Failed DD payment 3rd Feb',
    'CSC - Account Change',
    'CSC - ACS:Law Email Leak',
    'CSC - Automated Faults',
    'CSC - Automated Faults Enhanced Care',
    'CSC - B',
    'CSC - Billing',
    'CSC - Billing Chargeback',
    'CSC - Billing Discounts',
    'CSC - Billing non automated ceases',
    'CSC - Billing WLR component cancellation',
    'CSC - BT Fusion',
    'CSC - CS Billing alignments',
    'CSC - CS case management',
    'CSC - CS Escalations',
    'CSC - CS Letters',
    'CSC - Customer Services',
    'CSC - Deferred HW MAAF/ Wired',
    'CSC - Deferred HW MAAF/ Wireless',
    'CSC - Deferred HW Netgear N Trial (COT Use Only)',
    'CSC - Deferred HW Wired',
    'CSC - Deferred HW Wireless',
    'CSC - Dial Testing',
    'CSC - DSL Debt Recovery Removals',
    'CSC - DSL Debt Recovery Requests',
    'CSC - DSL DR Automated',
    'CSC - DSL Failed Billing',
    'CSC - DSL Failed Billing - Payment plans',
    'CSC - DSL Failed Billing - UI',
    'CSC - DSL Failed Billing Busine',
    'CSC - DSL Failed Billing Home',
    'CSC - DSL Failed Payment Home',
    'CSC - DSL Faults',
    'CSC - DSL Faults - Auth',
    'CSC - DSL Faults - Auth Enhanced Care',
    'CSC - DSL Faults - ccSFI',
    'CSC - DSL Faults - Intermittent',
    'CSC - DSL Faults - Intermittent Enhanced Care',
    'CSC - DSL Faults - LTB',
    'CSC - DSL Faults - No Sync',
    'CSC - DSL Faults - No Sync Enhanced Care',
    'CSC - DSL Faults - Retest',
    'CSC - DSL Faults - Speed',
    'CSC - DSL Faults - Speed Enhanced Care',
    'CSC - DSL Faults ADSL2',
    'CSC - DSL Faults ADSL2 - Auth',
    'CSC - DSL Faults ADSL2 - Intermittent',
    'CSC - DSL Faults ADSL2 - LTB',
    'CSC - DSL Faults ADSL2 - No Sync',
    'CSC - DSL Faults ADSL2 - Retest',
    'CSC - DSL Faults ADSL2 - Speed',
    'CSC - DSL Faults Enhanced Care',
    'CSC - End User DSL Faults - Speed',
    'CSC - Escalations Team',
    'CSC - Essential Pre-registration',
    'CSC - Failed Billing Grace Period',
    'CSC - Failed Billing Letters',
    'CSC - Failed Initial Fees',
    'CSC - Failed Initial Payment',
    'CSC - Failed Payment Business',
    'CSC - Failed Payment Grace Period',
    'CSC - Faults - AD',
    'CSC - Faults - CD',
    'CSC - Faults - CW',
    'CSC - Faults - DG',
    'CSC - Faults - DMa',
    'CSC - Faults - DMi',
    'CSC - Faults - Exchange Issues',
    'CSC - Faults - JB',
    'CSC - Faults - JE',
    'CSC - Faults - JF',
    'CSC - Faults - LK',
    'CSC - Faults - LW',
    'CSC - Faults - MA',
    'CSC - Faults - MF',
    'CSC - Faults - NG',
    'CSC - Faults - RS',
    'CSC - Faults - SC',
    'CSC - Faults - WC',
    'CSC - Faults CFT Testing DSL',
    'CSC - Faults CFT Testing DSL Logged',
    'CSC - Faults CFT Testing E-chat',
    'CSC - Faults CFT Testing Fibre',
    'CSC - Faults CFT Testing Fibre Logged',
    'CSC - Faults CFT Testing Home Phone',
    'CSC - Faults Hardware Tracking',
    'CSC - Faults queued for KBD testing',
    'CSC - Feedback',
    'CSC - Firmware Upgrades',
    'CSC - Framed Route Requests',
    'CSC - FTTC Faults',
    'CSC - FTTC Faults - Auth',
    'CSC - FTTC Faults - Equipment',
    'CSC - FTTC Faults - Intermittent',
    'CSC - FTTC Faults - Intermittent – Enhanced Care',
    'CSC - FTTC Faults - LTB',
    'CSC - FTTC Faults - No Sync',
    'CSC - FTTC Faults - Retest',
    'CSC - FTTC Faults - Speed',
    'CSC - FTTC Faults – Equipment – Enhanced Care',
    'CSC - G',
    'CSC - Hosting',
    'CSC - iPlates Feedback',
    'CSC - Jeopardy',
    'CSC - Letters',
    'CSC - Letters - Billing',
    'CSC - Manager Escalatio',
    'CSC - Market Changes',
    'CSC - Max Premium Offer',
    'CSC - Metronet TPAR',
    'CSC - Microfilters',
    'CSC - Network Administration',
    'CSC - Outbound Tickets',
    'CSC - Pornography Filter Campaign',
    'CSC - Real Time Cancellation',
    'CSC - Returned hardware DO NOT USE',
    'CSC - RTC - Automated Cease',
    'CSC - RTC - Do Not Use',
    'CSC - RTC - Invoice Removal',
    'CSC - RTC - LLU cease notifications',
    'CSC - RTC - Special Offers',
    'CSC - RTC Callbacks - In hours',
    'CSC - RTC Callbacks - Out of hou',
    'CSC - RTC DSR Right To Cancel (COT Use Only)',
    'CSC - RTC Escalations',
    'CSC - RTC Escalations COT USE ONLY',
    'CSC - RTC Essential Cancellations',
    'CSC - RTC Holding accounts COT USE ONLY',
    'CSC - RTC Internal cancellation requests',
    'CSC - RTC Letters',
    'CSC - RTC LLU In Hours - DO NOT USE',
    'CSC - RTC LLU OOH - DO NOT USE',
    'CSC - RTC Market Change (COT USE ONLY)',
    'CSC - RTC Oubound Fibre IH - DO NOT USE',
    'CSC - RTC Oubound Fibre OOH - DO NOT USE',
    'CSC - RTC Usage Refresh (COT USE ONLY)',
    'CSC - RTC-Discounts COT USE ONLY',
    'CSC - RTC-Instant Account Change-(COT USE ONLY)',
    'CSC - RTCC removal problem',
    'CSC - Sales - Special offer',
    'CSC - Sales TL Discount',
    'CSC - Signup with no MAC',
    'CSC - SMS Own Domain Check',
    'CSC - TC Faults',
    'CSC - TC Faults - Auth',
    'CSC - TC Faults - Intermittent',
    'CSC - TC Faults - No Sync',
    'CSC - TC Faults - Speed',
    'CSC - Team Managers',
    'CSC - Tech case management',
    'CSC - Thistle Billing',
    'CSC - Ticket Team (Billing)',
    'CSC - Ticket Team (Connection)',
    'CSC - Ticket Team (Email)',
    'CSC - Ticket Team (Evening)',
    'CSC - Ticket Team (Orders)',
    'CSC - Ticket Team (Products)',
    'CSC - Ticket Team (Referrals)',
    'CSC - Ticket Team (SafeGuard)',
    'CSC - Ticket Team (Speed)',
    'CSC - Ticket Team (Usage)',
    'CSC - Ticket Team (Weekend)',
    'CSC - Ticket Team OOH',
    'CSC - Ticket Team Second Line',
    'CSC - TV OOH',
    'CSC - TV Pre-registration',
    'CSC - TV Trial',
    'CSC - Unused 2',
    'CSC - V@H Brand Migrations',
    'CSC - Value to Extra usage refunds',
    'CSC - VAT invoices',
    'CSC - Voice Outbound',
    'CSC - VOIP SME',
    'CSC - VoIP Top-ups',
    'CSC - Webmail Setup',
    'CSC - WLR Component Cancellation Payment',
    'CSC - WLR final fees',
    'CSC - WLR WLT final fees',
    'CSC - £50 cashback offer',
    'CSC Analyst',
    'CSC Networks',
    'CSC RTC – Prolonged Personals COT USE ONLY',
    'CSC – RTC Broken Contract Addition (COT USE ONLY)',
    'CSC- Outbound (Webhelp) Trial',
    'CSC- RTC Market Change (COT USE ONLY)',
    'Customer Support Centre',
    'DC - CP',
    'DC - ISPA Testing 2012',
    'DC - ISPA Testing 2012 Refunds and Questions',
    'DC- Sam Knows Ofcom campaign',
    'Debt Management - Chargebacks',
    'Debt Management - COT Cancellation',
    'Debt Management - Debt Recovery Removals',
    'Debt Management - Debt Recovery Requests',
    'Debt Management - DR Automated',
    'Debt Management - Failed Initial Payment',
    'Debt Management - Grace Period',
    'Debt Management - Payment Plans',
    'Debt Management - RTC Automated Cease',
    'Debt Management - TV Cancellations',
    'Debt Management - WLR Component Cancellation',
    'Distressed Team CB/P',
    'Engineer charging - failed disputes',
    'GES Team',
    'HLE - AC',
    'HLE - AD',
    'HLE - AF',
    'HLE - AR',
    'HLE - AT',
    'HLE - AV',
    'HLE - AW',
    'HLE - BB',
    'HLE - CE',
    'HLE - CISAS',
    'HLE - CJ',
    'HLE - Complaints Manager',
    'HLE - CP',
    'HLE - Customer Services',
    'HLE - DC',
    'HLE - DG',
    'HLE - DH',
    'HLE - DN',
    'HLE - Escalations',
    'HLE - Executive',
    'HLE - Faults',
    'HLE - GB',
    'HLE - GM',
    'HLE - HB',
    'HLE - HF',
    'HLE - HH',
    'HLE - JB',
    'HLE - JC',
    'HLE - JDB',
    'HLE - JH',
    'HLE -',
    'HLE - JPWC',
    'HLE - JRB',
    'HLE - JS',
    'HLE - JT',
    'HLE - KA',
    'HLE - KC',
    'HLE - KLM',
    'HLE - KR',
    'HLE - KS',
    'HLE - Letters',
    'HLE - LK',
    'HLE - LL',
    'HLE - LS',
    'HLE - MA',
    'HLE - MB',
    'HLE - MC',
    'HLE - MP',
    'HLE - MS',
    'HLE - MT',
    'HLE - MW',
    'HLE - Ofcom',
    'HLE - Online Complaints',
    'HLE - PA',
    'HLE - Provisioning',
    'HLE - RB',
    'HLE - RG',
    'HLE - RN',
    'HLE - Satisfaction Survey',
    'HLE - SB',
    'HLE - SC',
    'HLE - Sec',
    'HLE - SL',
    'HLE - SS',
    'HLE - Survey Outbound',
    'HLE - Surveys',
    'HLE - Surveys Prov',
    'HLE - Technical Support',
    'HLE - TS',
    'HLE - TT',
    'Hostmaster',
    'IE - Business',
    'IE - CGI Migration',
    'IE - Generic',
    'IE - ITW Framed Route Requests',
    'IE - Mail',
    'IE - Mailspace Management',
    'IE - Traffic Management',
    'In Progress',
    'KBD Test Errors',
    'MAAF Recontracting',
    'Madasafish Talk Plan downgrades',
    'Marketing - Broadband Choices Case Studies',
    'Marketing - BTL25 fulfilment',
    'Marketing - Case Studies',
    'Marketing - Cashback claim',
    'Marketing - Community Username',
    'Marketing - DSLMax Opt Out',
    'Marketing - Fibre Trial Upgrades',
    'Marketing - ISPA',
    'Marketing - ISPA Refunds',
    'Marketing - JLBB Partner Offer Exceptions',
    'Marketing - John Lewis offer',
    'Marketing - LLU Opt Out',
    'Marketing - Max Premium Offer',
    'Marketing - uSwitch Case Studies',
    'Marketing - VF DO NOT USE',
    'Marketing - Voucher Fulfillment',
    'Marketing – Referrals 3mths Free Offer',
    'Missed appointments',
    'Partner',
    'Partner - Billing',
    'Partner - Faults',
    'Partner - Faults - Enhanced Care',
    'Partner - Hardware Ordering',
    'Partner - Technical',
    'Partner Approvals',
    'Partner Billing Ad Hoc',
    'Partner Management',
    'Partner Portal',
    'Partner Provisioning',
    'Partner Provisioning ADSL Esc',
    'Partner Provisioning SIM',
    'Partner PSTN Provisioning',
    'Partner Support',
    'PAYH - New Accounts',
    'PAYH - Support',
    'Plusnet Recontracting',
    'HP Q3 Special offer',
    'Priority - DJ',
    'Product Team',
    'Product Team - Devices Trial',
    'Product Team - SafeGuard Trial',
    'Products - E100 Wireshark Submissions',
    'Products - Fibre Trials',
    'Products - FTTC Trial',
    'Products - Port Requests',
    'Products - Static IP',
    'Products - TV Trial',
    'Products - VAS Data Requests',
    'Products - VoIP Beta Additions',
    'Products - VoIP Beta Generic',
    'Products - VoIP Beta Top-up',
    'Products - VoIP Migration',
    'Prov - Order cancelled',
    'Prov - Order Delayed',
    'Prov - Order Rejected',
    'Prov - Pega processing (automated)',
    'Prov - Rejected Cancel order',
    'Prov - Tentative appointments',
    'Prov - Waiters List',
    'Remote Internet - CSC',
    'Retention - Pro Special Offer',
    'RTC-Instant Account Change-(COT USE ONLY)',
    'Sales & COT',
    'Sales & COT Analyst',
    'Sign ups without MAC',
    'Supplier Management - BTW',
    'Supplier Management - OpenReach',
    'T2R - Cool BB (Trial)',
    'T2R - DLM Changes (Trial)',
    'Talk (WLR) - New Provides',
    'Tech - SS',
    'Technical Services',
    'Ticket Team - JRB',
    'Ticket Team - Services',
    'Training/Comms',
    'Unused - Directors',
    'Unused - HR - Training',
    'Unused - Management (ISP)',
    'Unused - Product Group',
    'UNUSED 2',
    'WBMC - Prov Test',
    'Web Design Team',
    'Web Development Team',
    'WLR component cancellation - DO NOT USE',
    'WLR10 Anytime Special Offer Team'
    ];
    
$allJLPPools = [
    'A&BS - Accounting, HR & Legal',
    'A&BS - Ceased line final fees',
    'A&BS - Cheque Refunds',
    'A&BS - Cheques awaiting allocation',
    'A&BS - Debt Recovery Removals',
    'A&BS - Debt Recovery Requests',
    'A&BS - Direct Debit Mandate Requests',
    'A&BS - DR Automated',
    'A&BS - HLE (Finance use only)',
    'A&BS - No longer in use',
    'A&BS - Part Payment Requests',
    'A&BS - Partner Accounts',
    'A&BS - Re-provide Auth',
    'A&BS - Refund Investigation',
    'Automated Script Pool',
    'Billing Operations - Billing Discounts',
    'Billing Operations - Billing, Refunds and Credits',
    'Billing Operations - Braille, Large Print or Audio Invoices',
    'Billing Operations - Chargebacks',
    'Billing Operations - Cheque refunds',
    'Billing Operations - Cheques awaiting allocation',
    'Billing-Ops-BT Sport Failed Payments',
    'BOT - ADSL Cease Requests',
    'BOT - Asset Checks',
    'BOT - Bauer CS',
    'BOT - Brand Migrations',
    'BOT - Delayed Orders',
    'BOT - Dispute No Access',
    'BOT - DSL Faults',
    'BOT - DSL Logged Appointments ADSL2',
    'BOT - DSL Logged Faults',
    'BOT - DSL Logged Faults - Auth',
    'BOT - DSL Logged Faults - Escala',
    'BOT - DSL Logged Faults - Interm',
    'BOT - DSL Logged Faults - LTB',
    'BOT - DSL Logged Faults - No Syn',
    'BOT - DSL Logged Faults - Post SFI',
    'BOT - DSL Logged Faults - Priority Team',
    'BOT - DSL Logged Faults - Priority Team Escalated',
    'BOT - DSL Logged Faults - Retest',
    'BOT - DSL Logged Faults - SFI',
    'BOT - DSL Logged Faults - Speed',
    'BOT - DSL Logged Faults ADSL2',
    'BOT - DSL Logged Faults ADSL2 - Auth',
    'BOT - DSL Logged Faults ADSL2 - Interm',
    'BOT - DSL Logged Faults ADSL2 - LTB',
    'BOT - DSL Logged Faults ADSL2 - No Sync',
    'BOT - DSL Logged Faults ADSL2 - Retest',
    'BOT - DSL Logged Faults ADSL2 - Speed',
    'BOT - DSL Migrations',
    'BOT - DSL Provisioning',
    'BOT - DSL Regrades',
    'BOT - DSL Regrades (Automated)',
    'BOT - End User DSL Logged Faults - Speed',
    'BOT - Engineer Charging disputes',
    'BOT - Escalated Appointments',
    'BOT - Expedite Orders',
    'BOT - Fibre Problems (Prov use only)',
    'BOT - FTTC Appointments',
    'BOT - FTTC Logged Faults',
    'BOT - FTTC Logged Faults - Appointments',
    'BOT - FTTC Logged Faults - Auth',
    'BOT - FTTC Logged Faults - Equip',
    'BOT - FTTC Logged Faults - Interm',
    'BOT - FTTC Logged Faults - LTB',
    'BOT - FTTC Logged Faults - No Sync',
    'BOT - FTTC Logged Faults - Post SFI',
    'BOT - FTTC Logged Faults - Priority Escalated',
    'BOT - FTTC Logged Faults - Speed',
    'BOT - FTTC Logged Faults – Speed – Enhanced Care',
    'BOT - FTTC Provides',
    'BOT - FTTC Provision Appointments',
    'BOT - FTTC Rejections',
    'BOT - HM Order placement',
    'BOT - Home Phone Nuisance Calls',
    'BOT - House Moves',
    'BOT - House Moves (In Progress)',
    'BOT - House Moves (Info required)',
    'BOT - House Moves BB Only',
    'BOT - House Moves NLI',
    'BOT - House Moves Start of Stop',
    'BOT - House Moves Transfer',
    'BOT - House Moves WLT',
    'BOT - Line Check Exception',
    'BOT - MPF WLR2',
    'BOT - New BB Order Placement',
    'BOT - New PSTN Provides',
    'BOT - Openreach Engineer appointments',
    'BOT - Phone Component',
    'BOT - Phone ELF',
    'BOT - Phone Faults',
    'BOT - Phone Faults - Logged',
    'BOT - Phone Faults - Logged Appointments',
    'BOT - Phone Faults - Migrations',
    'BOT - Phone Faults Escalations',
    'BOT - Phone Prov Cable Number port',
    'BOT - Phone Prov Cable Start of Stop',
    'BOT - Phone Provisioning',
    'BOT - Phone Provisioning MPF',
    'BOT - Phone provisioning WLT',
    'BOT - Priority DJ',
    'BOT - Priority GH',
    'BOT - Priority GR',
    'BOT - Priority MB',
    'BOT - Priority SW',
    'BOT - Provision Case Mgt BB',
    'BOT - Provision Case Mgt HP',
    'BOT - Regrades Due',
    'BOT - SDSL Faults',
    'BOT - SDSL Provisioning',
    'BOT - Simultaneous Provides',
    'BOT - Supplier Team',
    'BOT - Tags Queries',
    'BOT - Usage Resets',
    'BOT - WBMC Provisioning',
    'BOT - WLR 3 - Appointing',
    'BOT - WLR 3 - Cancelled Orders',
    'BOT - WLR 3 - Delayed Orders',
    'BOT - WLR 3 - Rejections',
    'BOT - WLR Directory Entry Changes',
    'BOT - WLR Feature Requests',
    'BOT - WLR Unsolicited Cease Cancellations',
    'BOT - WLR Worklist Items',
    'BOT - XML Rejections',
    'BOT WLR Provisioning Errors',
    'Broadband Update',
    'BTITW - Hardware Ordering',
    'Cancellation - Mac',
    'Complaints - Provisioning',
    'Complaints Advisor',
    'Consumer',
    'COT - Chat Use Only',
    'COT - HM CH',
    'COT - HM CW',
    'COT - HM DC',
    'COT - HM DG',
    'COT - HM Escalations',
    'COT - HM IN',
    'COT - HM JF',
    'COT - HM JV',
    'COT - HM LC',
    'COT - HM MC',
    'COT - HM MJ',
    'COT - HM Order placement',
    'COT - HM PL',
    'COT - HM SC',
    'COT - HM SH',
    'COT - HM SM',
    'COT – HM OOH',
    'COT – HM Priority',
    'COT – HM Reactivation',
    'CSC - Account Change',
    'CSC - Automated Faults',
    'CSC - B',
    'CSC - Billing',
    'CSC - Billing Chargeback',
    'CSC - Billing Discounts',
    'CSC - Billing non automated ceases',
    'CSC - Billing WLR component cancellation',
    'CSC - CS Billing alignments',
    'CSC - CS case management',
    'CSC - CS Escalations',
    'CSC - CS Letters',
    'CSC - Customer Services',
    'CSC - Deferred HW MAAF/ Wired',
    'CSC - Deferred HW MAAF/ Wireless',
    'CSC - Deferred HW Wired',
    'CSC - Deferred HW Wireless',
    'CSC - Dial Testing',
    'CSC - DSL Debt Recovery Removals',
    'CSC - DSL Debt Recovery Requests',
    'CSC - DSL DR Automated',
    'CSC - DSL Failed Billing Home',
    'CSC - DSL Failed Payment Home',
    'CSC - DSL Faults',
    'CSC - DSL Faults - Auth',
    'CSC - DSL Faults - ccSFI',
    'CSC - DSL Faults - Intermittent',
    'CSC - DSL Faults - LTB',
    'CSC - DSL Faults - No Sync',
    'CSC - DSL Faults - Retest',
    'CSC - DSL Faults - Speed',
    'CSC - DSL Faults ADSL2',
    'CSC - DSL Faults ADSL2 - Auth',
    'CSC - DSL Faults ADSL2 - Intermittent',
    'CSC - DSL Faults ADSL2 - LTB',
    'CSC - DSL Faults ADSL2 - No Sync',
    'CSC - DSL Faults ADSL2 - Retest',
    'CSC - DSL Faults ADSL2 - Speed',
    'CSC - Failed Billing Grace Period',
    'CSC - Failed Billing Letters',
    'CSC - Failed Initial Fees',
    'CSC - Failed Initial Payment',
    'CSC - Failed Payment Grace Period',
    'CSC - Faults - AD',
    'CSC - Faults - CD',
    'CSC - Faults - CW',
    'CSC - Faults - DG',
    'CSC - Faults - DMa',
    'CSC - Faults - DMi',
    'CSC - Faults - Exchange Issues',
    'CSC - Faults - JE',
    'CSC - Faults - JF',
    'CSC - Faults - LK',
    'CSC - Faults - LW',
    'CSC - Faults - MA',
    'CSC - Faults - MF',
    'CSC - Faults - NG',
    'CSC - Faults - RS',
    'CSC - Faults - SC',
    'CSC - Faults - WC',
    'CSC - Faults CFT Testing DSL',
    'CSC - Faults CFT Testing DSL Logged',
    'CSC - Faults CFT Testing E-chat',
    'CSC - Faults CFT Testing Fibre',
    'CSC - Faults CFT Testing Fibre Logged',
    'CSC - Faults CFT Testing Home Phone',
    'CSC - Faults Hardware Tracking',
    'CSC - Faults queued for KBD testing',
    'CSC - Firmware Upgrades',
    'CSC - FTTC Faults',
    'CSC - FTTC Faults - Auth',
    'CSC - FTTC Faults - Equipment',
    'CSC - FTTC Faults - Intermittent',
    'CSC - FTTC Faults - LTB',
    'CSC - FTTC Faults - No Sync',
    'CSC - FTTC Faults - Speed',
    'CSC - G',
    'CSC - Jeopardy',
    'CSC - Letters',
    'CSC - Letters - Billing',
    'CSC - Manager Escalatio',
    'CSC - Metronet TPAR',
    'CSC - Microfilters',
    'CSC - Network Administration',
    'CSC - Outbound Tickets',
    'CSC - Real Time Cancellation',
    'CSC - RTC - Automated Cease',
    'CSC - RTC - Do Not Use',
    'CSC - RTC - Invoice Removal',
    'CSC - RTC - LLU cease notifications',
    'CSC - RTC - Special Offers',
    'CSC - RTC DSR Right To Cancel (COT Use Only)',
    'CSC - RTC Escalations',
    'CSC - RTC Escalations COT USE ONLY',
    'CSC - RTC Essential Cancellations',
    'CSC - RTC Holding accounts COT USE ONLY',
    'CSC - RTC Internal cancellation requests',
    'CSC - RTC Letters',
    'CSC - RTC LLU OOH - DO NOT USE',
    'CSC - RTC Market Change (COT USE ONLY)',
    'CSC - RTC Usage Refresh (COT USE ONLY)',
    'CSC - RTC-Discounts COT USE ONLY',
    'CSC - RTC-Instant Account Change-(COT USE ONLY)',
    'CSC - Sales - Special offer',
    'CSC - Sales TL Discount',
    'CSC - Signup with no MAC',
    'CSC - SMS Own Domain Check',
    'CSC - Team Managers',
    'CSC - Team Managers HO Complaints',
    'CSC - Tech case management',
    'CSC - Ticket Team (Billing)',
    'CSC - Ticket Team (Connection)',
    'CSC - Ticket Team (Email)',
    'CSC - Ticket Team (Evening)',
    'CSC - Ticket Team (Orders)',
    'CSC - Ticket Team (Products)',
    'CSC - Ticket Team (Referrals)',
    'CSC - Ticket Team (Usage)',
    'CSC - Ticket Team (Weekend)',
    'CSC - Ticket Team OOH',
    'CSC - Ticket Team Second Line',
    'CSC - V@H Brand Migrations',
    'CSC - Value to Extra usage refunds',
    'CSC - VOIP SME',
    'CSC - WLR Component Cancellation Payment',
    'CSC - WLR final fees',
    'CSC - WLR WLT final fees',
    'CSC - £50 cashback offer',
    'CSC Analyst',
    'CSC RTC – Prolonged Personals COT USE ONLY',
    'CSC – RTC Broken Contract Addition (COT USE ONLY)',
    'CSC- Outbound (Webhelp) Trial',
    'Customer Support Centre',
    'DC - CP',
    'DC- Sam Knows Ofcom campaign',
    'Debt Management - Chargebacks',
    'Debt Management - COT Cancellation',
    'Debt Management - Debt Recovery Removals',
    'Debt Management - Debt Recovery Requests',
    'Debt Management - DR Automated',
    'Debt Management - Failed Initial Payment',
    'Debt Management - Grace Period',
    'Debt Management - Payment Plans',
    'Debt Management - RTC Automated Cease',
    'Debt Management - WLR Component Cancellation',
    'Distressed Team CB/P',
    'HLE - AC',
    'HLE - AD',
    'HLE - AR',
    'HLE - AT',
    'HLE - AV',
    'HLE - CE',
    'HLE - CISAS',
    'HLE - Complaints Manager',
    'HLE - CP',
    'HLE - Customer Services',
    'HLE - DG',
    'HLE - DH',
    'HLE - DN',
    'HLE - Escalations',
    'HLE - Executive',
    'HLE - Faults',
    'HLE - GM',
    'HLE - HB',
    'HLE - HF',
    'HLE - HH',
    'HLE - JB',
    'HLE - JC',
    'HLE - JDB',
    'HLE - JH',
    'HLE -',
    'HLE - JPWC',
    'HLE - JS',
    'HLE - JT',
    'HLE - KA',
    'HLE - KC',
    'HLE - KLM',
    'HLE - KR',
    'HLE - KS',
    'HLE - Letters',
    'HLE - LL',
    'HLE - LS',
    'HLE - MA',
    'HLE - MB',
    'HLE - MC',
    'HLE - MS',
    'HLE - MT',
    'HLE - MW',
    'HLE - Online Complaints',
    'HLE - Provisioning',
    'HLE - RB',
    'HLE - RG',
    'HLE - RN',
    'HLE - SB',
    'HLE - SC',
    'HLE - SL',
    'HLE - SS',
    'HLE - Technical Support',
    'HLE - TS',
    'HLE - TT',
    'Hostmaster',
    'IE - Generic',
    'IE - Mail',
    'IE - Mailspace Management',
    'IE - Traffic Management',
    'In Progress',
    'KBD Test Errors',
    'Marketing - JLBB Partner Offer Exceptions',
    'Partner',
    'Partner - Billing',
    'Partner Support',
    'Product Team',
    'Products - Fibre Trials',
    'Products - Port Requests',
    'Products - Static IP',
    'Prov - Order cancelled',
    'Prov - Order Delayed',
    'Prov - Order Rejected',
    'RTC-Instant Account Change-(COT USE ONLY)',
    'Sales & COT Analyst',
    'Supplier Management - BTW',
    'T2R - Cool BB (Trial)',
    'T2R - DLM Changes (Trial)',
    'Ticket Team - JRB',
    'Ticket Team - Services',
    'Training/Comms',
    'UNUSED - 5',
    'WLR component cancellation - DO NOT USE'
    ];